{
  config,
  lib,
  pkgs,
  ...
}:
with lib; let
  cfg = config.jitsi;
in {
  options.jitsi = {
    enable = mkEnableOption "Enable Jitsi";

    domain = mkOption {
      type = types.str;
      default = "jitsi.davidwild.ch";
    };
  };
  config = mkIf cfg.enable {
    nixpkgs.config.allowInsecurePredicate = pkg: builtins.elem (lib.getName pkg) [
      "jitsi-meet"
    ];
    services.jitsi-meet = {
      enable = true;
      hostName = cfg.domain;
      prosody.lockdown = true;
      config = {
        enableWelcomePage = false;
        prejoinPageEnabled = true;
        defaultLang = "en";
      };
      interfaceConfig = {
        SHOW_JITSI_WATERMARK = false;
        SHOW_WATERMARK_FOR_GUESTS = false;
      };
      nginx.enable = true;
    };
      services.jitsi-videobridge.openFirewall = true;
      networking.firewall.allowedTCPPorts = [ 80 443 5349 ];   # TURN-TLS
      networking.firewall.allowedUDPPorts = [ 10000 3478 ];    # media + TURN-UDP
      systemd.services.jitsi-videobridge2 = {
    wants    = [ "network-online.target" ];
    after    = [ "network-online.target" ];
    restartTriggers = [ config.environment.etc."jitsi/videobridge/sip-communicator.properties".source ];
  };
  environment.etc."jitsi/videobridge/sip-communicator.properties" = {
    text = ''
      # generated by NixOS – do not edit
      org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=192.168.0.29
      org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=${cfg.domain}
      org.ice4j.ice.harvest.USE_DYNAMIC_HOST_HARVESTER=false
      org.ice4j.ice.harvest.USE_DYNAMIC_JITTER_HARVESTER=false
    '';
    mode = "0644";
  };
    };
}
