# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.

# https://github.com/petm5/linux -> claims to have merged the patchs from the user who fixed the cameras
{ config, lib, pkgs, modulesPath, ... }:

let
  myCustomKernel = pkgs.callPackage
    ({ stdenv, fetchFromGitHub, buildLinux, ... }:
      buildLinux rec {
        version = "6.17.2";
        modDirVersion = version;
        src = fetchFromGitHub {
          owner = "petm5";
          repo = "linux";
          rev = "sp9-camera-enablement-6.17.2";
          sha256 = "sha256-VUkihnNE38iFHBP2H68+kgmV4dhalmYeC9ocfP5hvuw=";
        };

        defconfig = "x86_64_defconfig"; # adjust for your arch if needed

        # Optionally apply NixOS config fragments
        extraMeta.branch = "6.17";
        # structuredExtraConfig = with lib.kernel; {
        #   DEBUG_KERNEL = no;
        # };
      }) {};
in
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.kernelPackages = pkgs.linuxPackagesFor myCustomKernel;
  

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/62e0e6d3-473d-4e85-8b17-34f50e1835d1";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8407-14AE";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/a03d25a4-2ef2-4a02-83a4-090946857e35"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s13f0u2u1.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u1u2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
