  # Do not modify this file!  It was generated by ‘nixos-generate-config’                                                                                       
# and may be overwritten by future invocations.  Please make changes                                                                                          
# to /etc/nixos/configuration.nix instead.                                                                                                                    
{ config, lib, pkgs, modulesPath, ... }:                                                                                                                      
                                                                                                                                                              
{                                                                                                                                                             
  imports =                                                                                                                                                   
    [ (modulesPath + "/installer/scan/not-detected.nix")                                                                                                      
    ];


  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e76d05b8-36c5-444f-aa91-68132f366396";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F6E5-B90F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/3e9fb390-fe73-4790-8e45-82065889d0fc";
      fsType = "ext4";
    };
  fileSystems."/data1" = {
    device = "/dev/disk/by-uuid/28a8b55d-f715-443f-bd97-4ccf42db1ef6";
    fsType = "btrfs";
    options = ["defaults" "noatime" "compress=zstd" "nofail"];
  };

  fileSystems."/data2" = {
    device = "/dev/disk/by-uuid/da9aa6d9-7c0a-4ce2-956f-ebd19850ebfe";
    fsType = "btrfs";
    options = ["defaults" "noatime" "compress=zstd" "nofail"];
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/76bb8fdb-aba6-4626-afc4-d5ecc3ed60b7"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20u4.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
